### ISSUE TITLE
[EmailNotifier] testing email confirmation fails after successful registration

### ISSUE THREAD

**Issue by andres0sorio** [ecos-codeaholics/factory-of-procedures-back#18]
Testing the new email Notifier service (did not work on on windows). We need to test this - create a new Unitary test.

javax.mail.MessagingException: Exception reading response;
  nested exception is:
	java.net.SocketTimeoutException: Read timed out
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2202)
	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2087)
	at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:1889)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1120)

**Comment by andres0sorio** [comment]
Se captura la exception pero mensaje no dice mucho. Cambiar el mensaje de error.

**Comment by andres0sorio** [comment]
Revisado. Funcional. Cerrar.
